runtime: python27
api_version: 1
threadsafe: true


  
   
handlers:
- url: /my-style-dir
  static_dir: my-style-dir

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
